### ISSUE TITLE
Unable to establish websocket connection under firefox

### ISSUE THREAD

**Issue by extraymond** [http-rs/tide-websockets#5] opened 2020-12-20 06:28 UTC
Hi! I took the example and test with both firefox/chromium, while the chrome example worked, the firefox one failed.

After comparing the request headers, the chromium one has one additional bits then the firefox one in the **Sec-WebSocket-Extensions** header: **client_max_window_bits** and firefox got a bit more with **keep-alive** in the **Connection** header.
Any idea why this is happening?

test environment:

Firefox 85
Chromium: 87

Test script:
```js
let ws = new Websocket("ws://localhost:8080/");
```

**Comment by extraymond** [comment] 2020-12-20 09:11
Further investigation suggests that this is caused by hop-by-hop headers, which should be used by proxies.
If running tide server behind a proxy, eg Caddy, this doesn't cause any problems anymore.

However I'm not sure what should be the ideal solution, since it will forbid users to try websocket with tide using a firefox client directly.

**Comment by hoodie** [comment] 2021-01-01 19:52
> However I'm not sure what should be the ideal solution, since it will forbid users to try websocket with tide using a firefox client directly.
that's a no no! 😁
I don't quite understand the cause yet, but it seems to run into this [else](https://github.com/http-rs/tide-websockets/blob/main/src/handler.rs#L184)

**Comment by mankinskin** [comment] 2021-01-06 15:35
I might add that I get a `426 Upgrade Required` response from firefox requests to an endpoint `WebSocket` i.e.
```rust
fn wss_middleware() -> impl Middleware<()> + Endpoint<()> {
    WebSocket::new(async move |_, ws| {
        let (sink, stream) = ws.split();
        let stream = stream.map(|msg| msg.map(|msg| msg.into_data()));
        let sink = sink.with(async move |msg| Ok(Message::from(msg)) as Result<_, tide_websockets::Error>);
        websocket::connection(stream, sink).await;
        Ok(())
    })
}
async fn wss_handler(request: Request<()>) -> tide::Result {
    wss_middleware().call(request).await
}
...
server.at("/wss").get(wss_handler);
```
whereas chrome only gets `101 Switching Protocols` responses.

Seems like Firefox makes different kinds of requests and tide or tide-websockets doesn't interpret the upgrade requests by firefox correctly.

However the only difference that I can see in the request headers is that firefox sends a `Connection: keep-alive, Upgrade` instead of just `Upgrade` like chrome.

**Comment by mankinskin** [comment] 2021-01-06 15:43
Judging by [this line](https://docs.rs/tide-websockets/0.1.0/src/tide_websockets/handler.rs.html#130), the `Connection: keep-alive, upgrade` might be the problem. `WebSocket` is only interpreting requests as `Upgrades` if `Connection` excatly matches `Upgrade`.

**Comment by pepoviola** [comment] 2021-01-06 15:51
Hi @mankinskin, yes I also think that is the problem. I think this PR will fix that https://github.com/http-rs/tide-websockets/pull/8 .
Thanks!

**Comment by mankinskin** [comment] 2021-01-06 18:13
This fixes the 426 Upgrade Required response, and Firefox is getting 101 Switching Protocols, but the websocket connection is still not being started on Firefox, that is, the closure passed to `WebSocket::new` is not being executed.

**Comment by mu2019** [comment] 2021-01-08 03:18
fixup the firefox pros
https://github.com/http-rs/async-h1/pull/173

**Comment by extraymond** [comment] 2021-01-19 00:57
@jbr Should I close this as resolved? Or does it need some testing as well?

**Comment by pepoviola** [comment] 2021-01-23 11:16
Hi @jbr, now that both prs ( here and https://github.com/http-rs/async-h1/pull/173 ) we can close this one and we need to make `patch`  releases for both `tide-websockets` and `async-h1` right?

Thx!

**Comment by bnjbvr** [comment] 2021-02-04 16:38
Just wanted to let you know that I ran into this issue as well, and I could confirm it's fixed by using the main branch of `async-h1` in a fork of tide, and using the fork of tide as a dependency here!

**Comment by jbr** [comment] 2021-02-04 22:58
I'll run a release of both tide-websockets and async-h1 today

**Comment by jbr** [comment] 2021-02-04 23:12
resolved by the combination of https://github.com/http-rs/async-h1/releases/tag/v2.3.1 and https://github.com/http-rs/tide-websockets/releases/tag/v0.2.0

**Closed by jbr** 2021-02-04 23:12 UTC
